#!/bin/bash
mvn install
sudo /dopa-vm/stratosphere/bin/meteor-scheduler.sh stop
sudo cp ./lib/* /dopa-vm/stratosphere/lib/
sudo cp ./bin/* /dopa-vm/stratosphere/bin/
sudo cp ./target/meteor-scheduler*.jar /dopa-vm/stratosphere/lib/
sudo /dopa-vm/stratosphere/bin/meteor-scheduler.sh start